# Generated by Django 2.2.13 on 2020-07-02 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0012_auto_20200525_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='sampled_tissue',
            field=models.ForeignKey(blank=True, help_text='An ontology term describing the tissue from which the specimen was collected. The use of UBERON is recommended.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabularies.SkosConcept'),
        ),
    ]
